# Generated by Django 5.2.8 on 2025-11-17 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('studio_name', models.CharField(max_length=255, verbose_name='Название фотостудии')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photographer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=50, verbose_name='Телефон клиента')),
                ('date', models.DateField(verbose_name='Дата фотосессии')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость фотосессии')),
                ('view_code', models.CharField(blank=True, editable=False, max_length=16, unique=True, verbose_name='Код для просмотра')),
                ('download_code', models.CharField(blank=True, editable=False, max_length=16, unique=True, verbose_name='Код для скачивания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='photostudio.photographer', verbose_name='Фотограф')),
            ],
        ),
        migrations.CreateModel(
            name='SessionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='session_photos/original/%Y/%m/%d/', verbose_name='Оригинал')),
                ('watermarked_image', models.ImageField(upload_to='session_photos/watermarked/%Y/%m/%d/', verbose_name='Фото с водяным знаком')),
                ('face_encoding', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photostudio.photosession')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Ф.И.О клиента')),
                ('client_phone', models.CharField(max_length=50, verbose_name='Телефон клиента')),
                ('paid_at', models.DateTimeField(verbose_name='Дата оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='photostudio.photographer', verbose_name='Фотограф')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='photostudio.photosession', verbose_name='Фотосессия')),
                ('photos', models.ManyToManyField(related_name='orders', to='photostudio.sessionphoto', verbose_name='Фотографии, которые скачал клиент')),
            ],
        ),
    ]
