# Generated by Django 5.2.8 on 2025-11-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostudio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionphoto',
            name='watermarked_image',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='session_photos/watermarked/%Y/%m/%d/', verbose_name='Фото с водяным знаком'),
        ),
    ]
