# Generated by Django 5.2.8 on 2025-11-18 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostudio', '0002_alter_sessionphoto_watermarked_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='studio_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='client_phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='download_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photostudio.photographer'),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='photosession',
            name='view_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='sessionphoto',
            name='original_image',
            field=models.ImageField(upload_to='photos/originals/'),
        ),
        migrations.AlterField(
            model_name='sessionphoto',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photostudio.photosession'),
        ),
        migrations.AlterField(
            model_name='sessionphoto',
            name='watermarked_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/watermarked/'),
        ),
    ]
