# Generated by Django 5.2.8 on 2025-11-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostudio', '0003_alter_photographer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoorder',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='orders', to='photostudio.sessionphoto', verbose_name='Фотографии, которые скачал клиент'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать клиентам')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='photostudio.photographer', verbose_name='Фотограф')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['photographer', 'name'],
            },
        ),
        migrations.AddField(
            model_name='photoorder',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='orders', to='photostudio.service', verbose_name='Выбранные услуги'),
        ),
    ]
