# Generated by Django 5.2.8 on 2025-11-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostudio', '0004_alter_photoorder_photos_service_photoorder_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosession',
            name='session_type',
            field=models.CharField(choices=[('REGULAR', 'Обычная'), ('SCHOOL', 'Школьная'), ('KINDERGARTEN', 'Детский сад'), ('ALBUM', 'Альбомная (школа / детский сад)')], default='REGULAR', max_length=20, verbose_name='Тип фотосессии'),
        ),
    ]
